# Custom collections
collections:
  blog:
    output: true
  tools:
    output: true

# HTML Compression settings
compress_html:
  clippings: all
  comments: all

# Build settings
sass:
  style: compressed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Ignore files
exclude:
- Dockerfile
- README.md
- 'Gem*'
- '*.sh'
