name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency: # disable parallel workflow runs
      group: build-deploy
      cancel-in-progress: false
    container:
      image: ruby:2.7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Stuart Sul"
          git config --global user.email "ssstuartss@gmail.com"

      - name: Build site
        id: image
        run: |
          bundle install
          bundle exec jekyll build

      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v4
        with:
          repository: StuartSul/StuartSul.github.io
          ref: master
          ssh-key: ${{ secrets.GP_REPO_DEPLOY_KEY }}
          path: gh-repo

      - name: Copy build artifact
        run: |
          rm -r gh-repo/*
          cp -R _site/* gh-repo/

      - name: Deploy site
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          cd gh-repo
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "${COMMIT_MSG}"
            git push
          else
            echo "No changes to commit"
          fi
